config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/players', to: 'players#index', as: 'players'
  get '/players/new', to: 'players#new', as: 'new_player'
  post '/players/new', to: 'players#new'
  get '/players/:id/edit', to: 'players#edit', as: 'edit_player'
  post '/players/:id/edit', to: 'players#edit'
  get '/players/:id', to: 'players#show', as: 'player'
  post '/players', to: 'players#create'
  patch '/players/:id', to: 'players#update'
  delete '/players/:id', to: 'players#delete'

  get '/teams', to: 'teams#index', as: 'teams'
  get '/teams/:id', to: 'teams#show', as: 'team'
  delete '/teams/:id', to: 'teams#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ActiveRecord::Base
    belongs_to :team, optional: true

    def self.highest_points_per_game
        @players = Player.all
        @players.map do |player| 
            player[:points_per_game]
        end.max
    end

    def self.highest_rebounds_per_game
        @players = Player.all
        @players.map do |player| 
            player[:rebounds_per_game]
        end.max
    end

    def self.highest_per_game(arg)
        @players = Player.all
        @players.map do |player|
            player[:"#{arg}_per_game"]
        end.max
    end
    
end

app/models/team.rb
class Team < ActiveRecord::Base
    has_many :players
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

    def index
        @players = Player.all
    end

    def new
        @player = Player.new
        @teams = Team.all
    end

    def create
        player = Player.create(player_params)
        redirect_to player_path(player)
    end

    def edit
        @player = Player.find(params[:id])
        @teams = Team.all
    end

    def update
        player = Player.find(params[:id])
        player.update(player_params)
        redirect_to player_path(player)
    end

    def show
        @player = Player.find(params[:id])
    end

    def delete
        player = Player.find(params[:id])
        player.destroy
        redirect_to players_path
    end

    private

    def player_params
        params.require(:player).permit(:name, :team_acronym, :team_name, :games_played, :minutes_per_game,
            :field_goals_attempted_per_game, :field_goals_made_per_game, :field_goal_percentage,
            :free_throw_percentage, :three_point_attempted_per_game, :three_point_made_per_game,
            :three_point_percentage, :points_per_game, :offensive_rebounds_per_game, :defensive_rebounds_per_game,
            :rebounds_per_game, :assists_per_game, :steals_per_game, :blocks_per_game, :turnovers_per_game,
            :player_efficiency_rating, :team_id)
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

    def index
        @teams = Team.all
    end

    def show
        @team = Team.find(params[:id])
        @players = @team.players
    end

    def delete
        @player = Player.find(params[:id])
        @player.destroy
        redirect_to teams_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NbaTeams</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<h3>Edit Player Profile for 2017-2018 NBA Season | <%= link_to "NBA Teams", teams_path %></h3>
<hr>
<br>
<%= form_for @player do |f| %>
    <%= f.label :name, "Player Name:" %>
    <%= f.text_field :name %>
    <br>
    Team:<%= f.collection_select :team_id, @teams, :id, :name, prompt: true %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/players/index.html.erb
<h3>2017-2018 NBA Players | <%= link_to "Teams", teams_path %></h3>
<%= button_to "Create Player", new_player_path %>
<hr>
<h3>Top Stats:</h3>
Points per Game: <%= @players.highest_per_game("points") %>
<br>
Rebounds per Game: <%= @players.highest_per_game("rebounds") %>
<br>
Assists per Game: <%= @players.highest_per_game("assists") %>
<br>
Blocks per Game: <%= @players.highest_per_game("blocks") %>
<br>
Steals per Game: <%= @players.highest_per_game("steals") %>
<hr>
<h3>Players:</h3>
<ul>
<% @players.sort.each do |player| %>
    <li><%= link_to player.name, player_path(player) %></li>
<% end %>
</ul>

app/views/players/new.html.erb
<h3>Create Player for 2017-2018 NBA Season | <%= link_to "NBA Teams", teams_path %></h3>
<hr>
<br>
<%= form_for @player do |f| %>
    <%= f.label :name, "Player Name:" %>
    <%= f.text_field :name %>
    <br>
    Team:<%= f.collection_select :team_id, @teams, :id, :name, prompt: true %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/players/show.html.erb
<h3><%= @player.name %> | <%= link_to @player.team.name.upcase, team_path(@player.team_id) %> | 2017-2018 Season</h3> 
<%= button_to "Edit #{@player.name.split.first}", edit_player_path(@player) %>
<%= button_to "Delete #{@player.name.split.first}", { action: "delete", id: @player.id}, method: :delete  %>
<hr>
Player Efficiency Rating: <b><%= @player.player_efficiency_rating %></b><br>
Games Played: <b><%= @player.games_played %></b><br>
Mins per Game: <b><%= @player.minutes_per_game %></b><br>
<br>
Points per Game: <b><%= @player.points_per_game %></b><br>
Rebounds per Game: <b><%= @player.rebounds_per_game %></b><br>
Assists per Game: <b><%= @player.assists_per_game %></b><br>
Blocks per Game: <b><%= @player.blocks_per_game %></b><br>
Steals per Game: <b><%= @player.steals_per_game %></b><br>
Turnovers per Game: <b><%= @player.turnovers_per_game %></b><br>
<br>
FGA per Game: <b><%= @player.field_goals_attempted_per_game %></b><br>   
FGM per Game: <b><%= @player.field_goals_made_per_game %></b><br>
Field Goal %: <b><%=@player.field_goal_percentage%>%</b><br>
<br>
TPA per Game: <b><%= @player.three_point_attempted_per_game %></b><br>
TPM per Game: <b><%= @player.three_point_made_per_game %></b><br>
Three Point %: <b><%=@player.three_point_percentage%>%</b><br>
<br>
Offensive Rebs per Game: <b><%= @player.offensive_rebounds_per_game %></b><br>
Defensive Rebs per Game: <b><%= @player.defensive_rebounds_per_game %></b><br>
Free Throw %: <b><%= @player.free_throw_percentage %>%</b><br>
</ul>
<br>
<%= link_to "Back to Players", players_path %>